<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >


    <xacro:macro name="box_with_fillet" params="x y z size_x size_y size_z fillet_radius material">
            <!-- logitudinal box -->
            <visual>
                <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
                <geometry>
                    <box size="${size_x} ${size_y-(2*fillet_radius)} ${size_z}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
            <!-- lateral box -->
            <visual>
                <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
                <geometry>
                    <box size="${size_x-(2*fillet_radius)} ${size_y} ${size_z}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
            <!-- cylinder1 -->
            <visual>
                <origin xyz="${x+((size_x/2)-fillet_radius)} ${y+((size_y/2)-fillet_radius)} ${z}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${size_z}" radius="${fillet_radius}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
            <!-- cylinder2 -->
            <visual>
                <origin xyz="${x+((size_x/2)-fillet_radius)} ${y-((size_y/2)-fillet_radius)} ${z}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${size_z}" radius="${fillet_radius}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
            <!-- cylinder3 -->
            <visual>
                <origin xyz="${x-((size_x/2)-fillet_radius)} ${y+((size_y/2)-fillet_radius)} ${z}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${size_z}" radius="${fillet_radius}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
            <!-- cylinder4 -->
            <visual>
                <origin xyz="${x-((size_x/2)-fillet_radius)} ${y-((size_y/2)-fillet_radius)} ${z}" rpy="0 0 0"/>
                <geometry>
                    <cylinder length="${size_z}" radius="${fillet_radius}"/>
                </geometry>
                <material name="${material}"/>
            </visual>
    </xacro:macro>



   




    <xacro:property name="w_radius" value="${wheel_radius}"/>
    <xacro:property name="w_width" value="${wheel_thickness}"/>
    <xacro:property name="w_mass" value="${wheel_mass}"/>
    <xacro:property name="w_color" value="black"/>
    <xacro:property name="rim_color" value="red"/>


    <xacro:macro name="insert_drive_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${w_radius}" length="${w_width}"/>
            </geometry>
            <material name="${w_color}"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${w_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${w_mass}" length="${w_width}" radius="${w_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </xacro:macro>


    <xacro:macro name="insert_wheel_rim">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.005 ${w_radius*1.2} ${w_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.005 ${w_radius*1.2} ${w_width+0.005}"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
            <geometry>
                <box size="0.005 ${w_radius*1.2} ${w_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${-pi/4}"/>
            <geometry>
                <box size="0.005 ${w_radius*1.2} ${w_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi/4}"/>
            <geometry>
                <box size="0.005 ${w_radius*1.2} ${w_width+0.005}"/>
            </geometry>
            <material name="${rim_color}"/>
        </visual>
    </xacro:macro>



    <!-- <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo> -->




    <!-- <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo> -->










     <xacro:macro name="insert_mesh_drive_wheel">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="$(find mobo_bot_description)/meshes/wheel.stl"/>
                <!-- <xacro:unless value="${gazebo_visual}">
                    <mesh filename="package://mobo_bot_description/meshes/wheel.stl"/>
                </xacro:unless>
                <xacro:if value="${gazebo_visual}">
                    <mesh filename="$(find mobo_bot_description)/meshes/wheel.stl"/>
                </xacro:if> -->
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="0.05" length="0.02"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="0.4" length="0.02" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </xacro:macro>


    <!-- <link name="left_wheel_link">
        <xacro:insert_mesh_drive_wheel/>
    </link>

    <xacro:gazebo_wheel_settings name="left_wheel_link"/> -->


    
</robot>