<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:include filename="part_macros.xacro"/>


    <xacro:property name="chassis_length" value="0.335"/>
    <xacro:property name="chassis_width" value="0.265"/>
    <xacro:property name="chassis_height" value="0.138"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>


    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>


    <xacro:include filename="part_macros.xacro"/>



     <!-- GAZEBO WHEEL PARAMETERS -->
    <xacro:macro name="gazebo_wheel_settings" params="name">
        <gazebo reference="${name}">
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
            <!-- <kp>${kp}</kp> -->
            <!-- <kd>${kd}</kd> -->
            <!-- <fdir1>${fdir}</fdir1> -->
            <minDepth>0.01</minDepth>
            <material>Gazebo/FlatBlack</material>
        </gazebo>
    </xacro:macro>




    <!-- BASE LINK -->

    <link name="base_link">

    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="${-wheel_offset_x} 0 ${-wheel_offset_z}"/>
    </joint>

    <link name="chassis">
        <xacro:box_with_fillet x="${chassis_length/2}" y="0" z="${chassis_height/2}" size_x="${chassis_length}" size_y="${chassis_width}" size_z="${chassis_height}" fillet_radius="0.05" material="orange"/>
        <!-- <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual> -->
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>









    <!-- LEFT WHEEL LINK -->

    

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <xacro:insert_drive_wheel/>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/FlatBlack</material>
    </gazebo>


    <!-- <joint name="left_wheel_rim_joint" type="fixed">
        <parent link="left_wheel"/>
        <child link="left_wheel_rim"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="left_wheel_rim">
        <xacro:insert_wheel_rim/>
    </link>

    <gazebo reference="left_wheel_rim">
        <material>Gazebo/Red</material>
    </gazebo> -->




    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <xacro:insert_drive_wheel/>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/FlatBlack</material>
    </gazebo>


    <!-- <joint name="right_wheel_rim_joint" type="fixed">
        <parent link="right_wheel"/>
        <child link="right_wheel_rim"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="right_wheel_rim">
        <xacro:insert_wheel_rim/>
    </link>

    <gazebo reference="right_wheel_rim">
        <material>Gazebo/Red</material>
    </gazebo> -->







    <!-- CASTER WHEEL LINK -->

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>